
dist: trusty
language: python
python:
- '3.6.1'
install:
- pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "thomasschuetz"
    token:
      secure: $SONARCUBE

script:
  - py.test
  - sonar-scanner -X
